import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const editorViewPath = resolve(__dirname, '..', 'EditorView.vue')
const editorViewSource = readFileSync(editorViewPath, 'utf-8')

describe('EditorView mobile quick actions', () => {
  it('renders a sticky mobile action bar with primary actions', () => {
    expect(editorViewSource).toContain('mobile-quick-actions')
    expect(editorViewSource).toContain('sm:hidden fixed bottom-0')
    expect(editorViewSource).toContain('模板库')
    expect(editorViewSource).toContain('保存草稿')
    expect(editorViewSource).toContain('草稿箱')
    expect(editorViewSource).toContain('更多操作')
  })

  it('provides local draft center dialog with history restore controls', () => {
    expect(editorViewSource).toContain('本地草稿箱')
    expect(editorViewSource).toContain('共 {{ localDraftHistory.length }} 条本地草稿')
    expect(editorViewSource).toContain('搜索草稿名称/课程/班级')
    expect(editorViewSource).toContain('filteredLocalDraftHistory.length')
    expect(editorViewSource).toContain('resolveLocalDraftDisplayNameForView(item)')
    expect(editorViewSource).toContain("item.snapshot.courseName || '未填课程'")
    expect(editorViewSource).toContain("{{ item.pinned ? '取消置顶' : '置顶' }}")
    expect(editorViewSource).toContain('重命名')
    expect(editorViewSource).toContain('清理未置顶')
    expect(editorViewSource).toContain('导出草稿')
    expect(editorViewSource).toContain('导入草稿')
    expect(editorViewSource).toContain('localDraftImportInputRef')
    expect(editorViewSource).toContain('handleExportLocalDrafts')
    expect(editorViewSource).toContain('triggerImportLocalDrafts')
    expect(editorViewSource).toContain('handleImportLocalDrafts')
    expect(editorViewSource).toContain('buildEditorLocalDraftImportPreview(')
    expect(editorViewSource).toContain('buildEditorLocalDraftImportPreviewMessage(')
    expect(editorViewSource).toContain('检测到重复时间戳草稿')
    expect(editorViewSource).toContain('保留本地版本（仅导入新增）')
    expect(editorViewSource).toContain('导入草稿预览')
    expect(editorViewSource).toContain('仅导入勾选草稿')
    expect(editorViewSource).toContain('全选')
    expect(editorViewSource).toContain('仅冲突')
    expect(editorViewSource).toContain('仅新增')
    expect(editorViewSource).toContain('仅看冲突')
    expect(editorViewSource).toContain('仅看已勾选')
    expect(editorViewSource).toContain('清空选择')
    expect(editorViewSource).toContain('确认导入')
    expect(editorViewSource).toContain('本地：')
    expect(editorViewSource).toContain('导入：')
    expect(editorViewSource).toContain('差异：')
    expect(editorViewSource).toContain('展开差异')
    expect(editorViewSource).toContain('置顶 {{ pinnedDraftCount }} / 未置顶 {{ unpinnedDraftCount }}')
    expect(editorViewSource).toContain('handleToggleLocalDraftPinned')
    expect(editorViewSource).toContain('handleRenameLocalDraft')
    expect(editorViewSource).toContain('handleClearUnpinnedLocalDrafts')
    expect(editorViewSource).toContain('与当前内容差异：{{ selectedLocalDraftDiff.changedCount }} 项')
    expect(editorViewSource).toContain('恢复草稿')
    expect(editorViewSource).toContain('清空草稿')
  })

  it('uses a mobile-safe two-row layout for quick actions', () => {
    expect(editorViewSource).toContain('px-3 pt-3 pb-[calc(0.75rem+env(safe-area-inset-bottom))] grid grid-cols-1 gap-2')
  })

  it('keeps unsaved-draft protection hooks for navigation and refresh', () => {
    expect(editorViewSource).toContain('onBeforeRouteLeave')
    expect(editorViewSource).toContain("window.addEventListener('beforeunload', handleBeforeUnload)")
    expect(editorViewSource).toContain("window.removeEventListener('beforeunload', handleBeforeUnload)")
    expect(editorViewSource).toContain('当前教案有未保存更改，确定离开吗？')
    expect(editorViewSource).toContain('persistLocalDraftBeforeLeave')
    expect(editorViewSource).toContain('shouldPersistLocalDraftOnLeave')
  })
})
