import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const editorViewPath = resolve(__dirname, '..', 'EditorView.vue')
const editorViewSource = readFileSync(editorViewPath, 'utf-8')
const tipTapEditorPath = resolve(__dirname, '..', '..', 'components', 'TipTapEditor.vue')
const tipTapEditorSource = readFileSync(tipTapEditorPath, 'utf-8')

describe('EditorView form and editor visual system', () => {
  it('uses BaseInput for core metadata fields in basic info card', () => {
    expect(editorViewSource).toContain("import BaseInput from '../components/ui/BaseInput.vue'")
    expect(editorViewSource).toContain('<BaseInput')
    expect(editorViewSource).toContain('v-model="form.title"')
    expect(editorViewSource).toContain('v-model="form.courseName"')
    expect(editorViewSource).toContain('v-model="form.className"')
    expect(editorViewSource).toContain('v-model="durationText"')
    expect(editorViewSource).toContain('v-model="form.methods"')
    expect(editorViewSource).toContain('v-model="form.resources"')
  })

  it('uses warm themed shell classes for TipTap editor container', () => {
    expect(tipTapEditorSource).toContain('tiptap-warm-shell')
    expect(tipTapEditorSource).toContain('tiptap-warm-toolbar')
    expect(tipTapEditorSource).toContain('tiptap-warm-content')
  })

  it('provides focus mode and collapsible section controls', () => {
    expect(editorViewSource).toContain('专注模式')
    expect(editorViewSource).toContain('收起正文分区')
    expect(editorViewSource).toContain("handleToggleEditorSectionCollapsed('objectives')")
  })

  it('provides section navigation panel for quick focus', () => {
    expect(editorViewSource).toContain('编辑导航')
    expect(editorViewSource).toContain('下一待补分区')
    expect(editorViewSource).toContain('editorSectionCompletionItems')
    expect(editorViewSource).toContain('activeEditorSection')
    expect(editorViewSource).toContain('当前分区')
  })

  it('shows process minute summary and quick align action', () => {
    expect(editorViewSource).toContain('环节分钟')
    expect(editorViewSource).toContain('对齐课时')
    expect(editorViewSource).toContain('handleAlignDurationWithProcessMinutes')
  })

  it('supports mobile next-incomplete navigation and view preference persistence', () => {
    expect(editorViewSource).toContain('handleMobileFocusNextIncompleteSection')
    expect(editorViewSource).toContain('EDITOR_VIEW_PREFERENCE_STORAGE_KEY')
    expect(editorViewSource).toContain('loadEditorViewPreferenceFromStorage')
  })

  it('adds structured process timeline assistant controls', () => {
    expect(editorViewSource).toContain('结构化时间轴')
    expect(editorViewSource).toContain('拖拽排序')
    expect(editorViewSource).toContain('当前设备建议使用上移/下移')
    expect(editorViewSource).toContain(':draggable="canUseTimelineDrag"')
    expect(editorViewSource).toContain('@dragstart="canUseTimelineDrag && handleStartProcessTimelineDraftDrag')
    expect(editorViewSource).toContain('@dragover.prevent="canUseTimelineDrag && handleDragOverProcessTimelineDraftStep')
    expect(editorViewSource).toContain('@drop.prevent="canUseTimelineDrag && handleDropProcessTimelineDraftStep')
    expect(editorViewSource).toContain('handleToggleProcessTimelineDraftStepCollapsed')
    expect(editorViewSource).toContain('handleToggleAllProcessTimelineDraftStepCollapsed')
    expect(editorViewSource).toContain('收起')
    expect(editorViewSource).toContain('展开')
    expect(editorViewSource).toContain('全部收起')
    expect(editorViewSource).toContain('全部展开')
    expect(editorViewSource).toContain('应用替换')
    expect(editorViewSource).toContain('应用追加')
    expect(editorViewSource).toContain('一键生成替换')
    expect(editorViewSource).toContain('上移')
    expect(editorViewSource).toContain('下移')
    expect(editorViewSource).toContain('草案对齐课时')
    expect(editorViewSource).toContain('handleApplyProcessTimelineDraft')
    expect(editorViewSource).toContain('handleAlignProcessTimelineDraftMinutes')
    expect(editorViewSource).toContain('handleResetProcessTimelineDraft')
    expect(editorViewSource).toContain('handleMoveProcessTimelineDraftStep')
    expect(editorViewSource).toContain('handleGenerateProcessTimeline')
    expect(editorViewSource).toContain('预览替换')
    expect(editorViewSource).toContain('预览追加')
    expect(editorViewSource).toContain('时间轴应用预览')
    expect(editorViewSource).toContain('showTimelineApplyPreviewDialog = ref(false)')
    expect(editorViewSource).toContain('handleOpenProcessTimelineApplyPreview')
    expect(editorViewSource).toContain('handleConfirmProcessTimelineApplyPreview')
    expect(editorViewSource).toContain('撤销草案')
    expect(editorViewSource).toContain('重做草案')
    expect(editorViewSource).toContain('handleUndoProcessTimelineDraft')
    expect(editorViewSource).toContain('handleRedoProcessTimelineDraft')
    expect(editorViewSource).toContain('selectedProcessTimelineDraftStepIds')
    expect(editorViewSource).toContain('批量删除选中')
    expect(editorViewSource).toContain('选中等分总分钟')
    expect(editorViewSource).toContain('选中对齐课时')
    expect(editorViewSource).toContain('选中+5分钟')
    expect(editorViewSource).toContain('选中-5分钟')
    expect(editorViewSource).toContain('补全空标签')
    expect(editorViewSource).toContain('handleAlignSelectedProcessTimelineDraftMinutesWithDuration')
    expect(editorViewSource).toContain('handleAdjustSelectedProcessTimelineDraftStepMinutes')
    expect(editorViewSource).toContain('handleAutofillSelectedProcessTimelineDraftStepLabels')
    expect(editorViewSource).toContain('buildEditorTimelineApplyPreviewDiff')
    expect(editorViewSource).toContain('已选 {{ selectedProcessTimelineDraftStepCount }} 项')
  })

  it('uses selectable topic candidates for lesson traceability instead of manual id input', () => {
    expect(editorViewSource).toContain('课程标准条目引用')
    expect(editorViewSource).toContain('v-model="lessonTopicSearch"')
    expect(editorViewSource).toContain('handleToggleLessonTopicRef(item.id)')
    expect(editorViewSource).toContain('全选筛选结果')
    expect(editorViewSource).toContain('清空已选')
    expect(editorViewSource).toContain('本周推荐')
    expect(editorViewSource).toContain('orphanLessonTopicRefs')
    expect(editorViewSource).not.toContain('v-model="lessonTopicRefsText"')
  })

  it('includes courseware traceability panel for lesson mode', () => {
    expect(editorViewSource).toContain('课件附件映证')
    expect(editorViewSource).toContain('loadLessonCoursewareAssets')
    expect(editorViewSource).toContain('handleCreateLessonCoursewareAsset')
    expect(editorViewSource).toContain('handleDeleteLessonCoursewareAsset')
    expect(editorViewSource).toContain('handleEditLessonCoursewareAsset')
    expect(editorViewSource).toContain('handleCancelEditLessonCoursewareAsset')
    expect(editorViewSource).toContain('handleAutofillLessonCoursewareAsset')
    expect(editorViewSource).toContain('handleAutofillAllMissingLessonCoursewareAssets')
    expect(editorViewSource).toContain('resolveCoursewareMissingFields')
    expect(editorViewSource).toContain('handleFocusLessonCoursewareSection')
    expect(editorViewSource).toContain('lessonWarningGroups')
    expect(editorViewSource).toContain('handleApplyLessonCoursewareBatchUpdate')
    expect(editorViewSource).toContain('selectedLessonCoursewareAssetIds')
    expect(editorViewSource).toContain('lessonCoursewareBatchForm')
    expect(editorViewSource).toContain('updateCoursewareAsset')
    expect(editorViewSource).toContain('handleResolveLessonWarning')
    expect(editorViewSource).toContain('resolveLessonWarningFixChecklist')
    expect(editorViewSource).toContain('lessonWarningFixChecklist')
    expect(editorViewSource).toContain('handleApplyLessonWarningAutofix')
    expect(editorViewSource).toContain('handleOpenLessonWarningWorkbench')
    expect(editorViewSource).toContain('buildLessonPublishWarningMessage')
    expect(editorViewSource).toContain("path: '/workbench'")
    expect(editorViewSource).toContain("source: 'editor-lesson-warning'")
    expect(editorViewSource).toContain('lesson-field-week-no')
    expect(editorViewSource).toContain('lesson-field-ideology')
    expect(editorViewSource).toContain('lesson-field-integration')
    expect(editorViewSource).toContain('lesson-field-topic-refs')
    expect(editorViewSource).toContain('发布前修复建议')
    expect(editorViewSource).toContain('lessonCoursewareAssets.length')
    expect(editorViewSource).toContain('添加课件附件')
    expect(editorViewSource).toContain('保存修改')
    expect(editorViewSource).toContain('取消编辑')
    expect(editorViewSource).toContain('批量覆盖已选')
    expect(editorViewSource).toContain('批量补齐缺失')
    expect(editorViewSource).toContain('一键补齐')
    expect(editorViewSource).toContain('一键补齐全部缺失')
  })

  it('aligns lesson-mode labels with classroom teaching template headings', () => {
    expect(editorViewSource).toContain('课堂教学教案头信息（No.x）')
    expect(editorViewSource).toContain('v-model="lessonContext.lessonType"')
    expect(editorViewSource).toContain('v-model="lessonContext.weekday"')
    expect(editorViewSource).toContain('v-model="lessonContext.period"')
    expect(editorViewSource).toContain('v-model="lessonContext.lessonDate"')
    expect(editorViewSource).toContain('v-model="lessonContext.difficulty"')
    expect(editorViewSource).toContain('v-model="lessonContext.teachingAids"')
    expect(editorViewSource).toContain("{{ isLessonEditorMode ? '教学目的和要求' : '教学目标' }}")
    expect(editorViewSource).toContain("{{ isLessonEditorMode ? '教学重点与难点' : '重点难点' }}")
    expect(editorViewSource).toContain("{{ isLessonEditorMode ? '授课提纲' : '教学过程' }}")
    expect(editorViewSource).toContain("{{ isLessonEditorMode ? '课后小结' : '教学反思' }}")
  })
})
